//priority: 1000

// Items added here will get recipes for Pedestals & Cobblegen Randomizer cobblegens.
const generatableCobblestone = [
    'minecraft:cobbled_deepslate',
    "blue_skies:turquoise_cobblestone",
    "blue_skies:lunar_cobblestone",
    'byg:dacite_cobblestone',
    'byg:ether_stone',
    'byg:purpur_stone',
    'byg:red_rock',
    'byg:scoria_cobblestone',
    'byg:soapstone',
    'byg:travertine',
    'undergarden:depthrock',
    'undergarden:shiverstone',
    'undergarden:tremblecrust',
    //'atmospheric:saffron_travertine',
    //'atmospheric:persimmon_travertine',
    //'atmospheric:peach_travertine',
    //'atmospheric:ivory_travertine',
    //'atum:limestone_cracked'
];
// Items added here will get recipes for Pedestals & Cobblegen Randomizer stonegens.
const generatableStone = [
    'minecraft:andesite',
    'minecraft:deepslate',
    'minecraft:diorite',
    'minecraft:granite',
    'minecraft:calcite',
    'minecraft:tuff',
    'minecraft:dripstone_block',
    //'betterendforge:flavolite',
    //'betterendforge:sulphuric_rock',
    //'betterendforge:violecite',
    "blue_skies:umber",
    "blue_skies:cinderstone",
    "blue_skies:taratite",
    "blue_skies:rimestone",
    "blue_skies:midnight_sandstone",
    "blue_skies:crystal_sandstone",
    'byg:black_sandstone',
    'byg:blue_sandstone',
    'byg:dacite',
    'byg:purple_sandstone',
    'byg:windswept_sandstone',
    'byg:pink_sandstone',
    'byg:scoria_stone',
    'byg:white_sandstone',
    'minecraft:red_sandstone',
    'minecraft:sandstone',
    'quark:dusky_myalite',
    'quark:soul_sandstone',
    'quark:jasper',
    'quark:limestone',
    'quark:myalite',
    'quark:permafrost',
    'quark:shale',
    //'astralsorcery:marble_raw',
    'create:asurine',
    'create:crimsite',
    'create:limestone',
    'create:ochrum',
    'create:scoria',
    'create:scorchia',
    'create:veridium',
    //'atmospheric:red_arid_sandstone',
    //'atmospheric:arid_sandstone',
    //'atum:alabaster',
    //'atum:porphyry',
];
const generatableBasalt = [];
