//priority: 1000

// Items added here will get recipes for Pedestals & Cobblegen Randomizer cobblegens.
const generatableCobblestone = [
    'byg:dacite_cobblestone',
    'byg:cobbled_ether_stone',
    'byg:purpur_stone',
    'byg:red_rock',
    'byg:scoria_cobblestone',
    'byg:soapstone',
    'byg:travertine',
    'undergarden:depthrock',
    'undergarden:shiverstone',
    'undergarden:tremblecrust',
    'minecraft:cobbled_deepslate',
    'blue_skies:turquoise_cobblestone'
];
// Items added here will get recipes for Pedestals & Cobblegen Randomizer stonegens.
const generatableStone = [
    'byg:black_sandstone',
    'byg:blue_sandstone',
    'byg:dacite',
    'byg:purple_sandstone',
    'byg:pink_sandstone',
    'byg:scoria_stone',
    'byg:white_sandstone',
    'minecraft:red_sandstone',
    'minecraft:sandstone',
    'minecraft:diorite',
    'minecraft:granite',
    'minecraft:andesite',
    'minecraft:deepslate',
    'byg:brimstone',
    'quark:jasper',
    'quark:limestone',
    'quark:permafrost',
    'create:scoria',
    'create:limestone',
    'quark:myalite',
    'quark:dusky_myalite',
    'blue_skies:turquoise_stone',
    'blue_skies:rimestone',
    'minecraft:dripstone_block',
    'quark:soul_sandstone',
    'blue_skies:midnight_sandstone',
    'blue_skies:lunar_stone',
    'blue_skies:crystal_sandstone',
    'blue_skies:blinding_stone',
    'blue_skies:nature_stone',
    'blue_skies:poison_stone',
    'byg:windswept_sandstone',
    'byg:ether_stone',
    'byg:cryptic_stone',
    'twilightforest:mazestone',
    'create:asurine',
    'minecraft:tuff',
    'create:crimsite',
    'create:ochrum',
    'create:scorchia',
    'create:veridium'
];
const generatableBasalt = [`minecraft:basalt`];

const excludeDuplicatesCobbleGen = [
    'byg:ether_stone',
    'minecraft:dripstone_block',
    'quark:jasper',
    'quark:limestone',
    'quark:permafrost',
    'create:scoria',
    'create:limestone',
    'quark:myalite',
    'quark:dusky_myalite',
    'byg:scoria_stone',
    'byg:dacite',
    'byg:purpur_stone',
    'byg:red_rock',
    'byg:scoria_cobblestone',
    'byg:soapstone',
    'byg:travertine',
    'undergarden:depthrock',
    'undergarden:shiverstone',
    'undergarden:tremblecrust',
    'byg:dacite_cobblestone',
    'minecraft:cobbled_deepslate',
    'minecraft:diorite',
    'minecraft:granite',
    'minecraft:andesite',
    'minecraft:deepslate',
    'blue_skies:turquoise_cobblestone',
    'create:asurine',
    'minecraft:tuff',
    'create:crimsite',
    'create:ochrum',
    'create:scorchia',
    'create:veridium'
];