//priority: 1001

const stones = [
    'minecraft:andesite',
    'minecraft:deepslate',
    'minecraft:diorite',
    'minecraft:granite',
    'minecraft:calcite',
    'minecraft:tuff',
    'minecraft:dripstone_block',
    'blue_skies:umber',
    'blue_skies:cinderstone',
    'blue_skies:taratite',
    'blue_skies:rimestone',
    'byg:dacite',
    'byg:scoria_stone',
    'quark:dusky_myalite',
    'quark:jasper',
    'quark:limestone',
    'quark:myalite',
    'quark:permafrost',
    'quark:shale',
    'create:asurine',
    'create:crimsite',
    'create:limestone',
    'create:ochrum',
    'create:scoria',
    'create:scorchia',
    'create:veridium'
];